version: '3.7'

services:
  main:
    container_name: shiksha-backend-oblf-digiocean
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: yarn run start:dev
    env_file:
      - .env
    networks:
      - webnet
    restart: always
networks:
  webnet:

