version: "3.6"

services:
  backend:
    image: shiksha-backend-2.0
    container_name: "shiksha-backend-2.0"
    restart: always
    ports:
      - 3000:3000
    env_file:
      - /home/ubuntu-backend-shiksha2.0/.env
