name: Deploy to QA
on:
  push:
    branches:
      - Shiksha-2.0
jobs:
   deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - 
      name: Deploy Stack
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST_NAME_PRATHAM_QA }}
          username: ${{ secrets.USERNAME_PRATHAM_QA }}
          key: ${{ secrets.EC2_SSH_KEY_PRATHAM_QA }}
          port: ${{ secrets.PORT_PRATHAM_QA }}
          script: |    
               cd ${{ secrets.TARGET_DIR_PRATHAM_QA }}
               ./deploy.sh
